### ISSUE TITLE
File is always empty

### ISSUE THREAD

**Issue by hazemhagrass** [rikkertkoppes/json2xls#11]
I tried the code in your example:
 ```
  var json = {
        foo: 'bar',
        qux: 'moo',
        poo: 123,
        stux: new Date()
    }

    var xls = json2xls(son);

    fs.writeFileSync(path, xls, 'binary');
```
but unfortunately the file in path is always empty

**Comment by kvermeille** [comment]
+1

**Comment by brightloudnoise** [comment]
looks like you have a typo on line 8.

var xls = json2xls(**son**);

should be: 

var xls = json2xls(**json**);

**Comment by rikkertkoppes** [comment]
See comment by @brightloudnoise 

For reference, this would be a complete working example:

    var json2xls = require('../lib/json2xls');
    var fs = require('fs');

    var json = {
        foo: 'bar',
        qux: 'moo',
        poo: 123,
        stux: new Date()
    }

    var xls = json2xls(json);

    fs.writeFileSync('output.xlsx', xls, 'binary');

Which results in the following excel sheet:
![image](https://cloud.githubusercontent.com/assets/302821/16514594/0e0b1588-3f6d-11e6-9fd4-c8d046a68d0d.png)
