### ISSUE TITLE
Example needed for fields option

### ISSUE THREAD

**Issue by swinston100** [rikkertkoppes/json2xls#17]
Hi,

First of all thanks for the great package, it's saved me loads of time in developing my app!

I have a field called Date and I am able to successfully pass an array as an option as follows:

`var fields = ["Date"]
`
However when I try and specify that i want Date to be let's say a number

`var fields = [{"Date": "number"}]
`
An unhandled error crashes my app

> \myapp\node_modules\json2xls\lib\json2xls.js:28
>     path = path.replace(/\[(\w+)\]/g, '.$1'); // convert indexes to properties
>                 ^
> 
> TypeError: path.replace is not a function
>     at getByString (C:\Users\steven\myapp\node_modules\json2xls\lib\json2xls.js:28:17)

I'm obviously not setting up the object correctly, can you show me how it's done please?

It would also be great if in future versions you could allow row width manipulation and the use of `beforeCellWrite `which I see on export-excel. And finally date support would be great - but I see another member has maybe already solved this one!

Thanks so much
Steven

**Comment by rikkertkoppes** [comment]
That would be 

    var fields = {"Date": "number"}

I'll update the readme
