### ISSUE TITLE
data for fields with numeric data is not exported.

### ISSUE THREAD

**Issue by ghost** [rikkertkoppes/json2xls#39]
I prepared the json with fieldname as `Mobile No.*` and value as a mobile number in string format. But in the output excel file, the field always comes as blank for all rows.

**Comment by ghost** [comment]
I found the issue. I had 'Mobile No.*' as the field name. I changed it to 'Mobile No.' and it is working now. I think it has to do something with the regular expression.

Hope this issue gets solved soon. Thanks.

**Comment by hall-a** [comment]
This package has not had any maintenance for a long time. I had the same issue as above. I created a fork and applied necessary fixes. Published via , [npm as @aquajax/json2xls](https://www.npmjs.com/package/@aquajax/json2xls)

**Comment by ghost** [comment]
Cool. Thanks for the update.
