### ISSUE TITLE
Not working properly with mozilla

### ISSUE THREAD

**Issue by bunty93** [rikkertkoppes/json2xls#4]
On saving the file in mozilla, it returns a zipped file and not the excel file required.

**Comment by fernandoguedes** [comment]
Could you explain better?

**Comment by bunty93** [comment]
![image](https://cloud.githubusercontent.com/assets/6351526/7305816/741a277e-ea1e-11e4-8471-73c68bc06c72.png)

Returns a zip folder containing all these files and folder.. Works fine on Chrome

**Comment by rikkertkoppes** [comment]
Can you share some code or a jsfiddle?

Also, if you rename the .zip to .xlsx, can you open it?

**Comment by bunty93** [comment]
Yeah i am able to open it on renaming the file so what might be the problem ?

**Comment by rikkertkoppes** [comment]
If you are passing the file contents as a data url to a download link, you
may need to tweak its contents type

Don't really know until you show some code

**Comment by bunty93** [comment]
Hey rikkertkoppes it's very badly written , still checkout the /xls/branchwise route
https://bitbucket.org/bunty93/markstudio/src/c9ea5ba24e3de1a193b7c57534810f719aab78ae/routes/excelgenerator.js?at=master

**Comment by rikkertkoppes** [comment]
Ah, that makes sense. Looks like the middleware is not using the correct content type. I'll look into it.

In the meantime, can you try not using the middleware, but serving up the content like this:

        var xls = transform(data,config);
        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader("Content-Disposition", "attachment; filename=" + fn);
        res.end(xls, 'binary');

It seems I implemented the incorrect content type: http://stackoverflow.com/questions/2937465/what-is-correct-content-type-for-excel-files

Let me know if it works, and I'll adjust the repo accordingly

**Comment by rikkertkoppes** [comment]
Also, judging by your icon pack, I assume you are running Ubuntu? A quick test on windows works just fine on Mozilla.

**Comment by rikkertkoppes** [comment]
Any luck with the above? I tried to reproduce your problem on ubuntu, but everything works just fine as is.

**Comment by bunty93** [comment]
I'm not able to implement the config thing inside transform...so, hadn't replied
