### ISSUE TITLE
Nested fields

### ISSUE THREAD

**Issue by razb** [rikkertkoppes/json2xls#6]
Does json2xls support nested fields? by default it lists the nested fields as objects without the contents

**Comment by rikkertkoppes** [comment]
Nope, no support. Could be better though. 

Any suggestions as to what to render in a cell if it is an object?

**Comment by razb** [comment]
I worked around it by using flat (https://www.npmjs.com/package/flat) to flatten the array of objects before  passing to json2xls. I think the approach used by flat would work great i.e. each nested field is listed hierarchically:

[ { a: 1,
    b: 2,
    c: { d: 3,
           e: 4
        }
  },
{ a: 5,
    b: 6,
    c: { d: 7,
           e: 8
        }
  }
]

=   
     a,b,c.d,c.e
     1,2,3,4
      5,6,7,8

**Comment by rikkertkoppes** [comment]
Nested fields are now supported by passing in a path in the fields config option. e.g:

    json2xsl(objectData,{
        fields:['nested.field']
    });
