### ISSUE TITLE
Include hyperlink

### ISSUE THREAD

**Issue by spat-ne-hochu** [rikkertkoppes/json2xls#7]
http://example.com must be export to hyperlink. Now it is simple text.

**Comment by rikkertkoppes** [comment]
I don't think that is currently possible. json2xls uses https://github.com/functionscope/Node-Excel-Export and adds very little excel options of its own.

You may have a closer look at what is possible with the styles.xml file (which can be passed as a second parameter), but I don't think it's in there: http://officeopenxml.com/SSstyles.php
